/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hse_application;

import java.awt.Color;
import java.awt.Image;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.ImageIcon;

import javax.swing.JDialog;

/**
 *
 * @author OPTIPLEX
 */
public class StudentInfoFrame extends javax.swing.JDialog {
   
    private Path path = Paths.get("C:\\HSE_Images");
    int xMouse;
    int yMouse;
    /**
     * Creates new form StudentInfoFrame
     */
    public StudentInfoFrame(JDialog owner) {
        super(owner);
        initComponents();
        
    }
    
    public void setDetails(String studno, String name, String email, String nationality, String dob,
            String emiratesid, String lastmodifieddate, byte [] picture, String contact, String branch){
        
//        Image image;
        
        
//        ImageIcon icon = new ImageIcon(picture);
         
         
//        String pathOfPicture = "C:\\Users\\OPTIPLEX\\Documents\\NetBeansProjects\\HSE_Application\\src\\hse_application\\hse_images\\"+studno+".png";
//        Path path = Paths.get(pathOfPicture);



        ///test
//        String pathOfPicture = path+"\\"+studno+".png";
//        Path checkIfPictureExists = Paths.get(pathOfPicture);
//        
//        if (Files.exists(checkIfPictureExists)){
//            ImageIcon e = new ImageIcon(pathOfPicture);
//            photo_bomb.setIcon(e);
//        }



        lbl_branch.setText(branch);
//        photo_bomb.setIcon(new javax.swing.ImageIcon(pathOfPicture));
        if (picture!=null){
            ImageIcon a = new ImageIcon(picture);
            photo_bomb.setIcon(a);
        }
        
        lbl_studentnumber.setText(studno);
        lbl_fullname.setText(name);
        
        
        if (contact==null || contact.isEmpty()){
            lbl_contact.setText(" - ");
        }else{
            lbl_contact.setText(contact);
        }
        
        if (email==null || email.isEmpty()){
            lbl_email.setText(" - ");
        }else{
            lbl_email.setText(email);
        }
        
        if (nationality==null || nationality.equalsIgnoreCase("null") || nationality.isEmpty()){
            lbl_nationality.setText("-");
        }else{
            lbl_nationality.setText(nationality);
        }
        
        
        if (dob==null || dob.isEmpty() || dob.equalsIgnoreCase("null")){
            lbl_dob.setText("-");
        }else{
            lbl_dob.setText(dob);
        }
        
        if (emiratesid==null){
            lbl_eid.setText("Not Available");
        }else{
            lbl_eid.setText(emiratesid);
        }
        
        if (lastmodifieddate==null){
            lbl_date.setText("N/A");
        }else{
            lbl_date.setText(lastmodifieddate);
        }
        
        String iconOfStatus;
        
        if (emiratesid==null){
            lbl_status.setText("Incomplete");
            lbl_status.setForeground(Color.red);
//            String iconOfStatus = "C:\\Users\\OPTIPLEX\\Documents\\NetBeansProjects\\HSE_Application\\src\\hse_application\\Icons\\warning.png";
            iconOfStatus = "/hse_application/Icons/warning.png";
            
            
        }else{
            lbl_status.setText("Complete");
            lbl_status.setForeground(new Color(0,153,0));
//            iconOfStatus = "C:\\Users\\OPTIPLEX\\Documents\\NetBeansProjects\\HSE_Application\\src\\hse_application\\Icons\\checked.png";
            iconOfStatus = "/hse_application/Icons/checked.png";
            
        }
        
        lbl_status.setIcon(new javax.swing.ImageIcon(getClass().getResource(iconOfStatus)));
        
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_header = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lbl_fullname = new javax.swing.JLabel();
        photo_bomb = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_studentnumber = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        lbl_nationality = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_eid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        lbl_branch = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(712, 699));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel1.setBackground(new java.awt.Color(234, 238, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 68, 124)));

        header.setBackground(new java.awt.Color(11, 68, 124));
        header.setPreferredSize(new java.awt.Dimension(705, 39));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hse_application/Icons/close (2).png"))); // NOI18N
        jButton4.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jButton4.text")); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setMargin(new java.awt.Insets(2, 10, 2, 8));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        header.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 0, -1, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hse_application/hse_images/Backgrounds/studentinfo.png"))); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel2.text")); // NOI18N
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 705, 39));

        lbl_header.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_header.text")); // NOI18N
        lbl_header.setPreferredSize(new java.awt.Dimension(710, 39));
        lbl_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_headerMouseDragged(evt);
            }
        });
        lbl_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_headerMousePressed(evt);
            }
        });
        header.add(lbl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        jTabbedPane1.setBackground(new java.awt.Color(234, 238, 243));

        jPanel3.setBackground(new java.awt.Color(234, 238, 243));

        lbl_fullname.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_fullname.setForeground(new java.awt.Color(20, 20, 20));
        lbl_fullname.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_fullname.text")); // NOI18N
        lbl_fullname.setToolTipText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_fullname.toolTipText")); // NOI18N
        lbl_fullname.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        photo_bomb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photo_bomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hse_application/Icons/question.png"))); // NOI18N
        photo_bomb.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.photo_bomb.text")); // NOI18N
        photo_bomb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 68, 124)));
        photo_bomb.setPreferredSize(new java.awt.Dimension(130, 154));

        lbl_status.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lbl_status.setForeground(new java.awt.Color(0, 153, 0));
        lbl_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hse_application/Icons/checked.png"))); // NOI18N
        lbl_status.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_status.text")); // NOI18N
        lbl_status.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lbl_statusComponentShown(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(95, 99, 104));
        jLabel7.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel7.text")); // NOI18N

        lbl_studentnumber.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_studentnumber.setForeground(new java.awt.Color(20, 20, 20));
        lbl_studentnumber.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_studentnumber.text")); // NOI18N

        lbl_contact.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_contact.setForeground(new java.awt.Color(20, 20, 20));
        lbl_contact.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_contact.text")); // NOI18N

        lbl_nationality.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_nationality.setForeground(new java.awt.Color(20, 20, 20));
        lbl_nationality.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_nationality.text")); // NOI18N

        lbl_dob.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_dob.setForeground(new java.awt.Color(20, 20, 20));
        lbl_dob.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_dob.text")); // NOI18N

        lbl_date.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(20, 20, 20));
        lbl_date.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_date.text")); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(234, 238, 243));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setPreferredSize(new java.awt.Dimension(6, 514));

        lbl_eid.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_eid.setForeground(new java.awt.Color(20, 20, 20));
        lbl_eid.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_eid.text")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 19)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(32, 33, 36));
        jLabel9.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel9.text")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(95, 99, 104));
        jLabel10.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel10.text")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(95, 99, 104));
        jLabel11.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel11.text")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(95, 99, 104));
        jLabel12.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel12.text")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(95, 99, 104));
        jLabel13.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel13.text")); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 19)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(32, 33, 36));
        jLabel14.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel14.text")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 19)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(32, 33, 36));
        jLabel15.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel15.text")); // NOI18N

        jLabel16.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(95, 99, 104));
        jLabel16.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel16.text")); // NOI18N

        jLabel17.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(95, 99, 104));
        jLabel17.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel17.text")); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(99, 151));

        lbl_email.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(20, 20, 20));
        lbl_email.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_email.text")); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(234, 238, 243));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setPreferredSize(new java.awt.Dimension(6, 514));

        jSeparator8.setBackground(new java.awt.Color(234, 238, 243));
        jSeparator8.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator8.setPreferredSize(new java.awt.Dimension(6, 514));

        jSeparator9.setBackground(new java.awt.Color(234, 238, 243));
        jSeparator9.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator9.setPreferredSize(new java.awt.Dimension(6, 514));

        jSeparator10.setBackground(new java.awt.Color(234, 238, 243));
        jSeparator10.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator10.setPreferredSize(new java.awt.Dimension(6, 514));

        jSeparator11.setBackground(new java.awt.Color(234, 238, 243));
        jSeparator11.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator11.setPreferredSize(new java.awt.Dimension(6, 514));

        jSeparator12.setBackground(new java.awt.Color(234, 238, 243));
        jSeparator12.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator12.setPreferredSize(new java.awt.Dimension(6, 514));

        jLabel19.setFont(new java.awt.Font("Calibri Light", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(95, 99, 104));
        jLabel19.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jLabel19.text")); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(99, 151));

        jSeparator13.setBackground(new java.awt.Color(234, 238, 243));
        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator13.setPreferredSize(new java.awt.Dimension(6, 514));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hse_application/Icons/DefaultButtons/okdefault.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jButton1.text")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hse_application/Icons/ClickedButtons/okclicked.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/hse_application/Icons/HoverButtons/okhover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_branch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lbl_branch.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_branch.setText(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.lbl_branch.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_studentnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 5, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(photo_bomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_eid, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(238, 238, 238))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lbl_branch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_studentnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dob)))
                    .addComponent(photo_bomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_contact, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_eid)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_date)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(StudentInfoFrame.class, "StudentInfoFrame.jPanel4.TabConstraints.tabTitle"), jPanel4); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_statusComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lbl_statusComponentShown
        
    }//GEN-LAST:event_lbl_statusComponentShown

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered

    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited

    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbl_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lbl_headerMouseDragged

    private void lbl_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lbl_headerMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentInfoFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_branch;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_eid;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_fullname;
    private javax.swing.JLabel lbl_header;
    private javax.swing.JLabel lbl_nationality;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_studentnumber;
    public javax.swing.JLabel photo_bomb;
    // End of variables declaration//GEN-END:variables
}
